using System.Text.Json.Serialization;
using Clawsharp.Providers.OpenAi;

namespace Clawsharp.Providers.OpenRouter;

/// <summary>Source-generated JSON serialization context for OpenRouter API models.</summary>
[JsonSerializable(typeof(OpenRouterRequest))]
[JsonSerializable(typeof(OpenRouterResponse))]
[JsonSerializable(typeof(OpenRouterChoice))]
[JsonSerializable(typeof(OpenRouterUsage))]
[JsonSerializable(typeof(OpenRouterPromptTokensDetails))]
[JsonSerializable(typeof(OpenRouterCompletionTokensDetails))]
[JsonSerializable(typeof(OpenRouterStreamChunk))]
[JsonSerializable(typeof(OpenRouterStreamChoice))]
[JsonSerializable(typeof(OpenRouterPlugin))]
[JsonSerializable(typeof(OpenRouterProviderPreferences))]
[JsonSerializable(typeof(OpenRouterKeyInfoResponse))]
[JsonSerializable(typeof(OpenRouterKeyInfo))]
[JsonSerializable(typeof(OpenRouterError))]
[JsonSerializable(typeof(OpenRouterModelsResponse))]
[JsonSerializable(typeof(OpenRouterModel))]
[JsonSerializable(typeof(OpenRouterModelPricing))]
[JsonSerializable(typeof(OpenRouterModelArchitecture))]
[JsonSerializable(typeof(OpenRouterTopProvider))]
[JsonSerializable(typeof(List<OpenRouterModel>))]
// Reused types from OpenAi namespace
[JsonSerializable(typeof(CompletionMessage))]
[JsonSerializable(typeof(MessageContent))]
[JsonSerializable(typeof(ContentPart))]
[JsonSerializable(typeof(ImageUrl))]
[JsonSerializable(typeof(FileContentData))]
[JsonSerializable(typeof(VideoUrl))]
[JsonSerializable(typeof(FunctionTool))]
[JsonSerializable(typeof(FunctionDefinition))]
[JsonSerializable(typeof(FunctionToolCall))]
[JsonSerializable(typeof(FunctionToolCallDetail))]
[JsonSerializable(typeof(StreamDelta))]
[JsonSerializable(typeof(StreamToolCall))]
[JsonSerializable(typeof(StreamFunction))]
[JsonSerializable(typeof(StreamOptions))]
[JsonSerializable(typeof(List<CompletionMessage>))]
[JsonSerializable(typeof(List<FunctionTool>))]
[JsonSerializable(typeof(List<OpenRouterChoice>))]
[JsonSerializable(typeof(List<FunctionToolCall>))]
[JsonSerializable(typeof(List<ContentPart>))]
[JsonSerializable(typeof(List<OpenRouterStreamChoice>))]
[JsonSerializable(typeof(List<StreamToolCall>))]
[JsonSerializable(typeof(List<OpenRouterPlugin>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(GeneratedImageContent))]
[JsonSerializable(typeof(GeneratedImageUrl))]
[JsonSerializable(typeof(List<GeneratedImageContent>))]
[JsonSerializable(typeof(AudioContentData))]
[JsonSerializable(typeof(StreamAudioDelta))]
[JsonSerializable(typeof(OpenRouterAudioConfig))]
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
internal partial class OpenRouterJsonContext : JsonSerializerContext;
