using Clawsharp.Core.Utilities;

namespace Clawsharp.Core;

/// <summary>A message received from a channel (user input).</summary>
public sealed record InboundMessage(
    /// <summary>The channel this message arrived on.</summary>
    ChannelName Channel,
    /// <summary>Identifier of the sender (user or chat ID).</summary>
    string SenderId,
    /// <summary>Display name of the sender.</summary>
    string SenderName,
    /// <summary>The text content of the message.</summary>
    string Text,
    /// <summary>Optional thread identifier for threaded conversations.</summary>
    string? ThreadId = null,
    /// <summary>Timestamp when the message arrived. Defaults to <see cref="DateTimeOffset.UtcNow"/>.</summary>
    DateTimeOffset? ArrivedAt = null,
    /// <summary>Optional image attachments.</summary>
    IReadOnlyList<ImageAttachment>? Images = null,
    /// <summary>Whether this message was generated by the heartbeat service.</summary>
    bool IsHeartbeat = false,
    /// <summary>Current sub-agent spawn depth (0 = top-level). Used by SpawnTool to enforce max nesting.</summary>
    int SpawnDepth = 0,
    /// <summary>Optional model override for this request (e.g. from a cron job). Overrides the default model.</summary>
    string? ModelOverride = null,
    /// <summary>Optional provider override for this request (e.g. from a cron job). Overrides the default provider.</summary>
    string? ProviderOverride = null
);