using System.Text.Json.Serialization;

namespace Clawsharp.Providers.OpenAi;

/// <summary>
/// An image generated by the model, returned in the assistant message's <c>images</c> array.
/// Contains a data URL (base64-encoded) or an HTTPS URL.
/// </summary>
internal sealed class GeneratedImageContent
{
    [JsonPropertyName("type")]
    public string Type { get; init; } = "image_url";

    [JsonPropertyName("image_url")]
    public GeneratedImageUrl? ImageUrl { get; init; }
}

/// <summary>URL container for a generated image.</summary>
internal sealed class GeneratedImageUrl
{
    [JsonPropertyName("url")]
    public string Url { get; init; } = "";
}
