// <auto-generated />
using System;
using Clawsharp.Analytics.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace clawsharp.Analytics.Sqlite.Migrations
{
    [DbContext(typeof(SqliteAnalyticsContext))]
    partial class SqliteAnalyticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Clawsharp.Analytics.Entities.ConversationThread", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("ConversationThreads", (string)null);
                });

            modelBuilder.Entity("Clawsharp.Analytics.Entities.InteractionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CacheSavingsUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConversationThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Thinking")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.HasIndex("ConversationThreadId");

                    b.HasIndex("Model");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Interactions", (string)null);
                });

            modelBuilder.Entity("Clawsharp.Analytics.Entities.InteractionMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InteractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.HasIndex("MessageType");

                    b.ToTable("InteractionMessages", (string)null);
                });

            modelBuilder.Entity("Clawsharp.Analytics.Entities.InteractionEntity", b =>
                {
                    b.HasOne("Clawsharp.Analytics.Entities.ConversationThread", null)
                        .WithMany()
                        .HasForeignKey("ConversationThreadId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Clawsharp.Analytics.Entities.InteractionMessageEntity", b =>
                {
                    b.HasOne("Clawsharp.Analytics.Entities.InteractionEntity", null)
                        .WithMany()
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
